name: New info
description: Founded some new info about existing bot? Inform us to update info.
title: "[NewInfo]: <title>"
labels: contribution, info
assignees: ''
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this info report!