name: New Bot
description: You founded new bot which is not in the list? Feel free to inform everybody.
title: "[NewBot]: <botname>"
labels: new bot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this info report!
        
        Please write down following information in order to analize it.
  - type: input
    id: botname
    attributes:
      label: Bot Name
      description: How bot shows himself in the game. (If this bot has no name or `void` name enter `[void]`)
      placeholder: ex. Name-Stealer
    validations:
      required: true
  - type: dropdown
    id: gamemode
    attributes:
      label: Gamemode
      description: In witch gamemode you found it?
      multiple: true
      options:
        - Offence/Defence
        - Capture the flag
        - Control points
        - King of the hill
        - Payload
        - Payload race
        - Others (Medieval, invation, etc.)
        - MANN Power
        - Pass time
  - type: textarea
    id: behavior
    attributes:
      label: Bot behavior
      description: What was a behavior of the bot? Name all things that you noticed.
      value: |
        1.
        2.
        3.
        ...
      render: markdown,
    validations:
      required: true

